In [1]:
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime, date

/home/metalab_legion/.local/lib/python3.10/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.2' currently installed).
  from pandas.core import (
/home/metalab_legion/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "


In [28]:
def rsi(prices, period=14):
    
    prices = np.array(prices)
    rsi = np.zeros_like(prices)
    
    deltas = np.diff(prices)
    prices_up = deltas*(np.sign(deltas) + 1)/2
    prices_down = -deltas*(1 - np.sign(deltas))/2
    
    
    for i in range(len(prices)):
        
        if i < period - 1:
            
            rsi[i] = np.nan
            
        else:
            
            rs = np.sum(prices_up[i - period+1:i+1])
            rs /= np.sum(prices_down[i - period+1:i+1]) + 1e-10
            rsi[i] = 100 - 100/(1+ rs)
            
    return rsi

In [30]:
def myrsi(prices, period=14):
    
    prices = np.array(prices)
    myrsi = np.zeros_like(prices)
    
    deltas = np.diff(prices)
    prices_up = deltas*(np.sign(deltas) + 1)/2
    prices_down = -deltas*(1 - np.sign(deltas))/2
    
    
    for i in range(len(prices)):
        
        if i < period - 1:
            
            myrsi[i] = np.nan
            
        else:
            
            CU = np.sum(prices_up[i - period+1:i+1])
            CD = np.sum(prices_down[i - period+1:i+1]) 
            myrsi[i] = (CU - CD)/(CU + CD)
            
    return rsi    

In [16]:
deltas

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1, -1, -2])

In [17]:
prices_up

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.])

In [18]:
prices_down

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 2.])

In [19]:
a = [1,2,3]
a[0:2]

[1, 2]